const educationEn = [
	{ institution: "Massachusetts Institute of Technology", location: "Cambridge, MA", program: "M.S., Engineering and Management", period: "2020 – 2022", items: ["Fellow, MIT System Design and Management Program, focused on applying systems thinking, engineering, and management to large-scale, complex technology challenges.", "Thesis: A Systems Theory Approach to Cybersecuring a Supervised Machine Learning System.", "Student Senator at MIT Sloan School of Management, representing 200 SDM students.", "Graduate Certificate in Technical Leadership from the MIT Engineering Leadership Program.", "Legatum Fellow, selected for MIT’s competitive 10–15 student entrepreneurship fellowship supporting principled leaders building ventures in emerging and growth markets."] },
	{ institution: "Pontificia Universidad Católica de Chile", location: "Chile", program: "B.S., Software Engineering", period: "2004 – 2010", items: ["Teaching Assistant for several classes, including Software Engineering, Computer Architectures Lab, and Computer Networks.", "Exchange student at the Technical University of Denmark."] },
];
const educationEs = [
	{ institution: "Massachusetts Institute of Technology", location: "Cambridge, MA", program: "M.S., Engineering and Management", period: "2020 – 2022", items: ["Fellow del programa MIT System Design and Management, enfocado en aplicar pensamiento sistémico, ingeniería y gestión a desafíos tecnológicos complejos y de gran escala.", "Tesis: A Systems Theory Approach to Cybersecuring a Supervised Machine Learning System.", "Senador estudiantil en MIT Sloan School of Management, representando a 200 estudiantes de SDM.", "Graduate Certificate in Technical Leadership del MIT Engineering Leadership Program.", "Legatum Fellow, seleccionado para un programa competitivo de emprendimiento de MIT de 10 a 15 estudiantes, orientado a líderes con principios que desarrollan proyectos en mercados emergentes y de crecimiento."] },
	{ institution: "Pontificia Universidad Católica de Chile", location: "Chile", program: "B.S., Ingeniería de Software", period: "2004 – 2010", items: ["Ayudante en diversos cursos, incluyendo Ingeniería de Software, Laboratorio de Arquitectura de Computadores y Redes de Computadores.", "Estudiante de intercambio en la Technical University of Denmark."] },
];
const experienceEn = [
	{ organization: "ZeroFox Inc.", location: "Chile", context: "External cybersecurity company", role: "Software Engineering Manager", period: "2022 – Present", items: ["Led several engineering teams across Impersonations, Data Platform, Attack Surface, and related cybersecurity product areas, distributed across five time zones.", "Led the creation of ZeroFox’s Attack Surface product from scratch, making it one of ZeroFox’s key product offerings.", "Mentored and grew future engineering leaders inside the company, doubling their number.", "Served as Hiring Lead for Engineering across the organization, improving hiring process efficiency while hiring 60+ engineers.", "Led ZeroFox’s Chile office, strengthening local team culture, communication rhythms, and employee engagement across the engineering organization."] },
	{ organization: "Cybersecurity at MIT Sloan (CAMS), MIT Sloan School of Management", location: "Cambridge, MA", context: "Interdisciplinary Consortium for Improving Critical Infrastructure Cybersecurity", role: "Research Assistant", period: "2021 – 2022", items: ["Researched cybersecurity for AI systems and cybersecurity as a competitive advantage for companies, publishing a paper at the Future of Information and Communication Conference."] },
	{ organization: "Magnet", location: "Chile", context: "Boutique software development company in Chile with 40 employees", role: "CEO & Founder", period: "2012 – 2020", items: ["Recruited and led a three-person sales team, growing company revenue to USD 1.5M in five years.", "Created the HR department from scratch, improving average employee retention from two to four years.", "Led projects including software for Chile’s immigration process, warehousing for one of Latin America’s largest retail companies, and ERP for one of Chile’s largest privately owned infrastructure companies."] },
	{ organization: "Hadza", location: "Chile", context: "Tech startup focused on video synchronization", role: "CTO & Co-Founder", period: "2011 – 2012", items: ["Led the technical side while raising a USD 250K seed round at a USD 4M valuation.", "Recruited and led a 10-person team to develop backend and mobile apps using patented video synchronization technology."] },
];
const experienceEs = [
	{ organization: "ZeroFox Inc.", location: "Chile", context: "Empresa de ciberseguridad externa", role: "Software Engineering Manager", period: "2022 – Presente", items: ["Lideré varios equipos de ingeniería en áreas de <strong>Impersonations</strong>, <strong>Data Platform</strong>, <strong>Attack Surface</strong> y productos relacionados de ciberseguridad, distribuidos en cinco zonas horarias.", "Lideré la creación desde cero del producto <strong>Attack Surface</strong> de ZeroFox, convirtiéndolo en una de las principales ofertas de producto de la compañía.", "Mentoreé y desarrollé futuros líderes de ingeniería dentro de la compañía, duplicando su número.", "Fui Hiring Lead de Ingeniería para toda la organización, mejorando la eficiencia del proceso de contratación mientras se contrataban más de 60 ingenieros.", "Lideré la oficina de ZeroFox en Chile, fortaleciendo la cultura local, los ritmos de comunicación y el compromiso del equipo dentro de la organización de ingeniería."] },
	{ organization: "Cybersecurity at MIT Sloan (CAMS), MIT Sloan School of Management", location: "Cambridge, MA", context: "Interdisciplinary Consortium for Improving Critical Infrastructure Cybersecurity", role: "Research Assistant", period: "2021 – 2022", items: ["Investigué ciberseguridad para sistemas de IA y ciberseguridad como ventaja competitiva para empresas, publicando un paper en la Future of Information and Communication Conference."] },
	{ organization: "Magnet", location: "Chile", context: "Empresa boutique de desarrollo de software con 40 empleados", role: "CEO y fundador", period: "2012 – 2020", items: ["Recluté y lideré un equipo comercial de tres personas, aumentando los ingresos a USD 1.5M en cinco años.", "Creé el área de RR.HH. desde cero, mejorando la retención promedio del equipo de dos a cuatro años.", "Lideré proyectos incluyendo software para el proceso migratorio de Chile, bodegaje para una de las mayores empresas de retail de Latinoamérica y ERP para una de las mayores empresas privadas de infraestructura en Chile."] },
	{ organization: "Hadza", location: "Chile", context: "Startup tecnológica enfocada en sincronización de video", role: "CTO y cofundador", period: "2011 – 2012", items: ["Lideré el lado técnico durante el levantamiento de una ronda seed de USD 250K a una valorización de USD 4M.", "Recluté y lideré un equipo de 10 personas para desarrollar backend y aplicaciones móviles con tecnología patentada de sincronización de video."] },
];

const academicEn = [
	{ organization: "Pontificia Universidad Católica de Chile, School of Engineering", location: "Chile", context: "University", role: "Adjunct Professor", period: "2025 – Present", items: ["Created and taught Computer Security, including syllabus, class structure, homework, and course materials."] },
	{ organization: "Universidad de los Andes, School of Engineering", location: "Chile", context: "University", role: "Adjunct Professor", period: "2013 – 2021", items: ["Taught Software Engineering and Data Structures to more than 500 students over eight years."] },
];
const academicEs = [
	{ organization: "Pontificia Universidad Católica de Chile, Escuela de Ingeniería", location: "Chile", context: "Universidad", role: "Profesor adjunto", period: "2025 – Presente", items: ["Creé y dicté Seguridad Computacional, incluyendo programa, estructura del curso, tareas y materiales."] },
	{ organization: "Universidad de los Andes, Escuela de Ingeniería", location: "Chile", context: "Universidad", role: "Profesor adjunto", period: "2013 – 2021", items: ["Dicté Ingeniería de Software y Estructuras de Datos a más de 500 estudiantes durante ocho años."] },
];

const leadershipEn = [
	{ organization: "MITI", location: "Chile", context: "Technology industry association", role: "President", period: "2017 – 2019", items: ["Expanded the organization’s membership base by bringing in new technology companies and strengthening its industry network."] },
	{ organization: "Chiletec", location: "Chile", context: "Association of Chilean technology companies", role: "Board Member", period: "2019 – 2021", items: ["Worked closely with Chile’s Digital Government Division to improve conditions for software development and digital transformation in the public sector."] },
	{ organization: "MIT Alumni Chile", location: "Chile", context: "MIT alumni association in Chile", role: "Board Member", period: "2024 – Present", items: ["Supported outreach to newly admitted MIT students from Chile and helped organize events that strengthened interaction across the local alumni community."] },
];
const leadershipEs = [
	{ organization: "MITI", location: "Chile", context: "Asociación gremial de empresas de tecnología", role: "Presidente", period: "2017 – 2019", items: ["Expandí la base de socios de la organización incorporando nuevas empresas tecnológicas y fortaleciendo su red dentro de la industria."] },
	{ organization: "Chiletec", location: "Chile", context: "Asociación de Empresas Chilenas de Tecnología", role: "Director", period: "2019 – 2021", items: ["Trabajé de cerca con la Dirección de Gobierno Digital para mejorar las condiciones para el desarrollo de software y la transformación digital en el sector público."] },
	{ organization: "MIT Alumni Chile", location: "Chile", context: "Asociación de exalumnos del MIT en Chile", role: "Director", period: "2024 – Presente", items: ["Apoyé actividades de acercamiento a nuevos estudiantes chilenos admitidos en MIT y ayudé a organizar eventos para fortalecer la interacción de la comunidad local de exalumnos."] },
];

export const cv = {
	en: { lang: "en", altPath: "/es/cv/", title: "CV · Ignacio Parada", description: "Curriculum vitae for Ignacio Parada, software engineering leader, entrepreneur, and educator.", nav: { home: "Home", repos: "Repos", email: "Email" }, sectionLabels: { education: "Education", experience: "Professional Experience", academic: "Academic Experience", leadership: "Leadership & Board Service", additional: "Additional Information" }, contact: "yo@ignacioparada.com · +56 9 9872 6389 · linkedin.com/in/iparada", education: educationEn, experience: experienceEn, academic: academicEn, leadership: leadershipEn, print: "Print / Save as PDF", additional: [{ label: "Languages:", text: "Spanish native or bilingual, English native or bilingual, Italian limited working proficiency." }, { label: "Programs:", text: "Alumnus of Georgetown’s Global Competitiveness Leadership Program and Stanford Ignite." }, { label: "Hobbies:", text: "Tennis player since age eight." }] },
	es: { lang: "es", altPath: "/cv/", title: "CV · Ignacio Parada", description: "Currículum de Ignacio Parada, líder de ingeniería de software, emprendedor y profesor.", nav: { home: "Inicio", repos: "Repos", email: "Email" }, sectionLabels: { education: "Educación", experience: "Experiencia Profesional", academic: "Experiencia Académica", leadership: "Liderazgo y Directorios", additional: "Información adicional" }, contact: "yo@ignacioparada.com · +56 9 9872 6389 · linkedin.com/in/iparada", education: educationEs, experience: experienceEs, academic: academicEs, leadership: leadershipEs, print: "Imprimir / Guardar como PDF", additional: [{ label: "Idiomas:", text: "Español nativo o bilingüe, inglés nativo o bilingüe, italiano competencia profesional limitada." }, { label: "Programas:", text: "Exalumno del Global Competitiveness Leadership Program de Georgetown y de Stanford Ignite." }, { label: "Hobbies:", text: "Jugador de tenis desde los ocho años." }] },
};
