const educationEn = [
	{ institution: "Massachusetts Institute of Technology", location: "Cambridge, MA", program: "M.S., Engineering and Management", period: "2020 – 2022", items: ["Fellow, System Design and Management Program.", "Thesis: A Systems Theory Approach to Cybersecuring a Supervised Machine Learning System.", "Student Senator at MIT Sloan, representing 200 SDM students.", "Graduate Certificate in Technical Leadership from the MIT Engineering Leadership Program.", "Legatum Fellow.", "Relevant classes: Distributed Systems, Computer Systems Security, Leading Creative Teams."] },
	{ institution: "Pontificia Universidad Católica de Chile", location: "Chile", program: "B.S., Software Engineering", period: "2004 – 2010", items: ["Teaching Assistant for several classes, including Software Engineering, Computer Architectures Lab, and Computer Networks.", "Exchange student at the Technical University of Denmark."] },
];
const educationEs = [
	{ institution: "Massachusetts Institute of Technology", location: "Cambridge, MA", program: "M.S., Engineering and Management", period: "2020 – 2022", items: ["Fellow del programa System Design and Management.", "Tesis: A Systems Theory Approach to Cybersecuring a Supervised Machine Learning System.", "Student Senator en MIT Sloan, representando a 200 estudiantes de SDM.", "Graduate Certificate in Technical Leadership del MIT Engineering Leadership Program.", "Legatum Fellow.", "Cursos relevantes: Distributed Systems, Computer Systems Security, Leading Creative Teams."] },
	{ institution: "Pontificia Universidad Católica de Chile", location: "Chile", program: "B.S., Ingeniería de Software", period: "2004 – 2010", items: ["Ayudante en diversos cursos, incluyendo Ingeniería de Software, Laboratorio de Arquitectura de Computadores y Redes de Computadores.", "Estudiante de intercambio en la Technical University of Denmark."] },
];
const experienceEn = [
	{ organization: "ZeroFox Inc.", location: "Chile", context: "External cybersecurity company", role: "Software Engineering Manager", period: "2022 – Present", items: ["Led several engineering teams across impersonations, data platform, attack surface, and related cybersecurity product areas, distributed across five time zones.", "Led the creation of ZeroFox’s Attack Surface product from scratch, reaching USD 13M in revenue.", "Mentored and grew future engineering leaders inside the company, doubling their number.", "Served as Hiring Lead for Engineering across the organization, improving hiring process efficiency while hiring 60+ engineers."] },
	{ organization: "Pontificia Universidad Católica de Chile, School of Engineering", location: "Chile", context: "University", role: "Adjunct Professor", period: "2025 – Present", items: ["Created and taught Computer Security, including syllabus, class structure, homework, and course materials."] },
	{ organization: "Cybersecurity at MIT Sloan (CAMS), MIT Sloan School of Management", location: "Cambridge, MA", context: "Interdisciplinary Consortium for Improving Critical Infrastructure Cybersecurity", role: "Research Assistant", period: "2021 – 2022", items: ["Researched cybersecurity for AI systems and published a paper at the Future of Information and Communication Conference."] },
	{ organization: "Magnet", location: "Chile", context: "Boutique software development company in Chile with 40 employees", role: "CEO & Founder", period: "2012 – 2020", items: ["Recruited and led a three-person sales team, growing company revenue to USD 1.5M in five years.", "Created the HR department from scratch, improving average employee retention from two to four years.", "Acted as Product Manager for a cash-flow management platform implemented internally and as a SaaS product.", "Led development of a software platform used by LATAM Airlines to manage operational limitations for a fleet of 315 aircraft across 137 destinations.", "Led projects including software for Chile’s immigration process, warehousing for one of Latin America’s largest retail companies, and ERP for one of Chile’s largest privately owned infrastructure companies."] },
	{ organization: "Universidad de los Andes, School of Engineering", location: "Chile", context: "University", role: "Adjunct Professor", period: "2013 – 2021", items: ["Taught Software Engineering and Data Structures to more than 500 students over eight years."] },
	{ organization: "Hadza", location: "Chile", context: "Tech startup focused on video synchronization", role: "CTO & Co-Founder", period: "2011 – 2012", items: ["Led the technical side while raising a USD 250K seed round at a USD 4M valuation.", "Recruited and led a 10-person team to develop backend and mobile apps using patented video synchronization technology."] },
];
const experienceEs = [
	{ organization: "ZeroFox Inc.", location: "Chile", context: "Empresa de ciberseguridad externa", role: "Software Engineering Manager", period: "2022 – Presente", items: ["Lideré varios equipos de ingeniería en áreas de impersonations, data platform, attack surface y productos relacionados de ciberseguridad, distribuidos en cinco zonas horarias.", "Lideré la creación desde cero del producto Attack Surface de ZeroFox, alcanzando USD 13M en ingresos.", "Mentoricé y desarrollé futuros líderes de ingeniería dentro de la compañía, duplicando su número.", "Fui Hiring Lead de Ingeniería para toda la organización, mejorando la eficiencia del proceso de contratación mientras se contrataban más de 60 ingenieros."] },
	{ organization: "Pontificia Universidad Católica de Chile, Escuela de Ingeniería", location: "Chile", context: "Universidad", role: "Profesor adjunto", period: "2025 – Presente", items: ["Creé y dicté Seguridad Computacional, incluyendo programa, estructura del curso, tareas y materiales."] },
	{ organization: "Cybersecurity at MIT Sloan (CAMS), MIT Sloan School of Management", location: "Cambridge, MA", context: "Interdisciplinary Consortium for Improving Critical Infrastructure Cybersecurity", role: "Research Assistant", period: "2021 – 2022", items: ["Investigué ciberseguridad para sistemas de IA y publiqué un paper en la Future of Information and Communication Conference."] },
	{ organization: "Magnet", location: "Chile", context: "Empresa boutique de desarrollo de software con 40 empleados", role: "CEO y fundador", period: "2012 – 2020", items: ["Recluté y lideré un equipo comercial de tres personas, aumentando los ingresos a USD 1.5M en cinco años.", "Creé el área de RR.HH. desde cero, mejorando la retención promedio del equipo de dos a cuatro años.", "Actué como Product Manager de una plataforma de gestión de flujo de caja implementada internamente y como producto SaaS.", "Lideré el desarrollo de una plataforma usada por LATAM Airlines para gestionar limitaciones operacionales de una flota de 315 aviones en 137 destinos.", "Lideré proyectos incluyendo software para el proceso migratorio de Chile, bodegaje para una de las mayores empresas de retail de Latinoamérica y ERP para una de las mayores empresas privadas de infraestructura en Chile."] },
	{ organization: "Universidad de los Andes, Escuela de Ingeniería", location: "Chile", context: "Universidad", role: "Profesor adjunto", period: "2013 – 2021", items: ["Dicté Ingeniería de Software y Estructuras de Datos a más de 500 estudiantes durante ocho años."] },
	{ organization: "Hadza", location: "Chile", context: "Startup tecnológica enfocada en sincronización de video", role: "CTO y cofundador", period: "2011 – 2012", items: ["Lideré el lado técnico durante el levantamiento de una ronda seed de USD 250K a una valorización de USD 4M.", "Recluté y lideré un equipo de 10 personas para desarrollar backend y aplicaciones móviles con tecnología patentada de sincronización de video."] },
];

export const cv = {
	en: { lang: "en", altPath: "/es/cv/", title: "CV · Ignacio Parada", description: "Curriculum vitae for Ignacio Parada, software engineering leader, entrepreneur, and educator.", nav: { home: "Home", repos: "Repos", email: "Email" }, sectionLabels: { education: "Education", experience: "Experience", additional: "Additional Information" }, contact: "yo@ignacioparada.com · +56 9 9872 6389 · linkedin.com/in/iparada", education: educationEn, experience: experienceEn, print: "Print / Save as PDF", additional: [{ label: "Languages:", text: "Spanish native or bilingual, English native or bilingual, Italian limited working proficiency." }, { label: "Technical skills:", text: "Java, Python, C#, Golang, Android SDK." }, { label: "Volunteer experience:", text: "Co-founder and president of MITI, a Chilean NGO uniting software consulting companies; Board Member at Chiletec, a chamber of commerce with 200+ technology companies." }, { label: "Programs:", text: "Alumnus of Georgetown’s Global Competitiveness Leadership program." }, { label: "Hobbies:", text: "Tennis player since age eight." }] },
	es: { lang: "es", altPath: "/cv/", title: "CV · Ignacio Parada", description: "Currículum de Ignacio Parada, líder de ingeniería de software, emprendedor y profesor.", nav: { home: "Inicio", repos: "Repos", email: "Email" }, sectionLabels: { education: "Educación", experience: "Experiencia", additional: "Información adicional" }, contact: "yo@ignacioparada.com · +56 9 9872 6389 · linkedin.com/in/iparada", education: educationEs, experience: experienceEs, print: "Imprimir / Guardar como PDF", additional: [{ label: "Idiomas:", text: "Español nativo o bilingüe, inglés nativo o bilingüe, italiano competencia profesional limitada." }, { label: "Habilidades técnicas:", text: "Java, Python, C#, Golang, Android SDK." }, { label: "Voluntariado:", text: "Cofundador y presidente de MITI, ONG chilena que reúne empresas de consultoría de software; director en Chiletec, cámara de comercio con más de 200 empresas tecnológicas." }, { label: "Programas:", text: "Exalumno del Global Competitiveness Leadership Program de Georgetown." }, { label: "Hobbies:", text: "Jugador de tenis desde los ocho años." }] },
};
