export const home = {
	en: {
		lang: "en",
		altPath: "/es/",
		description: "Ignacio Parada is an entrepreneur, software engineering leader, and educator based in Santiago, Chile.",
		nav: { cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Entrepreneur · Engineering Leader · Educator",
		title: "I build technology companies, products, and teams.",
		lede: "I’m Ignacio Parada, a software engineering leader and entrepreneur based in Santiago, Chile. I’ve built and scaled technology companies, led distributed cybersecurity teams, and created software products across startups, enterprise, public-sector, and academic contexts.",
		actions: { cv: "View CV", repos: "View repos", linkedin: "View LinkedIn" },
		highlightsLabel: "Highlights",
		highlights: [
			{ title: "Company building", text: "Built and led Magnet over seven years, growing revenue to USD 1.5M, expanding its client portfolio, and scaling the company through sales, operations, culture, and finance." },
			{ title: "Engineering leadership", text: "Led distributed engineering teams at ZeroFox across Impersonations, Data Platform, Attack Surface, and related cybersecurity product areas." },
			{ title: "Cybersecurity, teaching & systems", text: "MIT SDM graduate, CAMS research assistant, and adjunct professor at Pontificia Universidad Católica de Chile, focused on cybersecurity, software systems, and technology leadership." },
		],
		footer: ["Santiago, Chile", "Spanish · English · Italian"],
	},
	es: {
		lang: "es",
		altPath: "/",
		description: "Ignacio Parada es emprendedor, líder de ingeniería de software y profesor en Santiago, Chile.",
		nav: { cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Emprendedor · Líder de ingeniería · Profesor",
		title: "Construyo compañías, productos y equipos de tecnología.",
		lede: "Soy Ignacio Parada, líder de ingeniería de software y emprendedor basado en Santiago, Chile. He construido y escalado compañías de tecnología, liderado equipos distribuidos de ciberseguridad y creado productos de software en startups, empresas, sector público y academia.",
		actions: { cv: "Ver CV", repos: "Ver repos", linkedin: "Ver LinkedIn" },
		highlightsLabel: "Destacados",
		highlights: [
			{ title: "Construcción de compañías", text: "Construí y lideré Magnet durante siete años, aumentando los ingresos a USD 1.5M, expandiendo su cartera de clientes y escalando la empresa en ventas, operaciones, cultura y finanzas." },
			{ title: "Liderazgo de ingeniería", text: "Lideré equipos de ingeniería distribuidos en ZeroFox en áreas de Impersonations, Data Platform, Attack Surface y productos relacionados de ciberseguridad." },
			{ title: "Ciberseguridad, docencia y sistemas", text: "Graduado del programa SDM de MIT, research assistant en CAMS y profesor adjunto en la Pontificia Universidad Católica de Chile, enfocado en ciberseguridad, sistemas de software y liderazgo tecnológico." },
		],
		footer: ["Santiago, Chile", "Español · Inglés · Italiano"],
	},
};

export const repos = {
	en: {
		lang: "en",
		altPath: "/es/repos/",
		description: "Selected public and private repositories by Ignacio Parada.",
		title: "Repositories · Ignacio Parada",
		nav: { home: "Home", cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Code & projects",
		heading: "Repositories I’m working with.",
		lede: "A short map of selected repositories, spanning teaching material, infrastructure automation, OpenClaw tooling, and this site itself. Private repositories are listed for context, but are not publicly accessible.",
		publicLabel: "Public",
		privateLabel: "Private",
		view: "View on GitHub →",
		privateNote: "Private repository — access restricted",
		footer: ["Santiago, Chile", "Public and private repository overview"],
	},
	es: {
		lang: "es",
		altPath: "/repos/",
		description: "Repositorios públicos y privados seleccionados de Ignacio Parada.",
		title: "Repositorios · Ignacio Parada",
		nav: { home: "Inicio", cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Código y proyectos",
		heading: "Repositorios en los que trabajo.",
		lede: "Un mapa breve de repositorios seleccionados: material docente, automatización de infraestructura, herramientas de OpenClaw y este sitio. Los repositorios privados aparecen solo como contexto y no son accesibles públicamente.",
		publicLabel: "Público",
		privateLabel: "Privado",
		view: "Ver en GitHub →",
		privateNote: "Repositorio privado — acceso restringido",
		footer: ["Santiago, Chile", "Resumen de repositorios públicos y privados"],
	},
};

export const repoItems = [
	{ name: "homepage", visibility: "Public", url: "https://github.com/nachoparada/homepage", stack: "Astro · JavaScript", description: { en: "The source for this personal website, built with Astro and deployed automatically through Cloudflare Pages.", es: "El código fuente de este sitio personal, construido con Astro y desplegado automáticamente mediante Cloudflare Pages." } },
	{ name: "IIC2531", visibility: "Public", url: "https://github.com/nachoparada/IIC2531", stack: "Marp · Markdown", description: { en: "Course material and Marp presentations for IIC2531, Computer Security at Pontificia Universidad Católica de Chile.", es: "Material del curso y presentaciones en Marp para IIC2531, Seguridad Computacional en la Pontificia Universidad Católica de Chile." } },
	{ name: "IIC2531-26-01-labs", visibility: "Public", url: "https://github.com/nachoparada/IIC2531-26-01-labs", stack: "Python · C · Shell · Assembly", description: { en: "Lab material and supporting code for the 2026-01 edition of IIC2531, focused on practical computer security exercises.", es: "Material de laboratorios y código de apoyo para la versión 2026-01 de IIC2531, enfocado en ejercicios prácticos de seguridad computacional." } },
	{ name: "disc-mods", visibility: "Private", url: null, stack: "OpenClaw · Agent skills · Security validation", description: { en: "Private extended-skill modules for sandboxed agents in The Grid, enabling privileged operations through validated, security-aware disc-mod packages.", es: "Módulos privados de habilidades extendidas para agentes sandboxed en The Grid, que permiten operaciones privilegiadas mediante paquetes validados y conscientes de seguridad." } },
	{ name: "io-tower", visibility: "Private", url: null, stack: "Chrome Extension · Browser automation", description: { en: "Private OpenClaw browser relay extension that connects a browser to OpenClaw Gateway for remote AI-powered navigation, clicking, typing, and extraction.", es: "Extensión privada de navegador para OpenClaw que conecta el browser con OpenClaw Gateway para navegación, clicks, escritura y extracción asistidas por IA." } },
	{ name: "nexus", visibility: "Private", url: null, stack: "Python · HTML · Shell", description: { en: "Private multi-server management system for OpenClaw deployments, used to monitor servers, collect configuration, track agents and disc-mods, and coordinate deployments.", es: "Sistema privado de gestión multi-servidor para despliegues de OpenClaw, usado para monitorear servidores, recolectar configuración, rastrear agentes y disc-mods, y coordinar despliegues." } },
	{ name: "the-grid", visibility: "Private", url: null, stack: "Ansible · OpenClaw · Infrastructure", description: { en: "Private Ansible deployment system for OpenClaw: automated, hardened host setup with security posture, service configuration, and operational automation.", es: "Sistema privado de despliegue Ansible para OpenClaw: configuración automatizada y endurecida de hosts, postura de seguridad, configuración de servicios y automatización operacional." } },
	{ name: "openclaw-ansible", visibility: "Public", url: "https://github.com/nachoparada/openclaw-ansible", stack: "Shell · Ansible · Jinja", description: { en: "Automated, hardened OpenClaw installation with Tailscale VPN, UFW firewall, Docker isolation, and multi-OS deployment support.", es: "Instalación automatizada y endurecida de OpenClaw con VPN Tailscale, firewall UFW, aislamiento Docker y soporte multi-OS." } },
];
