export const home = {
	en: {
		lang: "en",
		altPath: "/es/",
		description: "Ignacio Parada is an entrepreneur, software engineering leader, and educator based in Santiago, Chile.",
		nav: { cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Entrepreneur · Engineering Leader · Educator",
		title: "I build and lead technology teams.",
		lede: "I’m Ignacio Parada, a software engineering leader and entrepreneur based in Santiago, Chile. I’ve built products, companies, and teams across startups, cybersecurity, enterprise software, and academia — usually somewhere between strategy, engineering, and execution.",
		actions: { cv: "View CV", repos: "View repos", linkedin: "View LinkedIn" },
		highlightsLabel: "Highlights",
		highlights: [
			{ title: "Engineering leadership", text: "Led distributed engineering teams across multiple time zones at ZeroFox, including work across impersonations, data platforms, and attack surface products." },
			{ title: "Entrepreneurship", text: "Founded and grew Magnet from a small software company into a 45-person team delivering critical systems for major Latin American organizations." },
			{ title: "Teaching & systems", text: "MIT SDM graduate and adjunct professor at Pontificia Universidad Católica de Chile, focused on computer security, software systems, and how teams make technology work." },
		],
		footer: ["Santiago, Chile", "Spanish · English · Italian"],
	},
	es: {
		lang: "es",
		altPath: "/",
		description: "Ignacio Parada es emprendedor, líder de ingeniería de software y profesor en Santiago, Chile.",
		nav: { cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Emprendedor · Líder de ingeniería · Profesor",
		title: "Construyo y lidero equipos de tecnología.",
		lede: "Soy Ignacio Parada, líder de ingeniería de software y emprendedor basado en Santiago, Chile. He construido productos, compañías y equipos en startups, ciberseguridad, software empresarial y academia — normalmente entre estrategia, ingeniería y ejecución.",
		actions: { cv: "Ver CV", repos: "Ver repos", linkedin: "Ver LinkedIn" },
		highlightsLabel: "Destacados",
		highlights: [
			{ title: "Liderazgo de ingeniería", text: "Lideré equipos de ingeniería distribuidos en múltiples zonas horarias en ZeroFox, incluyendo áreas de impersonations, plataformas de datos y productos de attack surface." },
			{ title: "Emprendimiento", text: "Fundé y escalé Magnet desde una pequeña empresa de software hasta un equipo de 45 personas, desarrollando sistemas críticos para grandes organizaciones latinoamericanas." },
			{ title: "Docencia y sistemas", text: "Graduado del programa SDM de MIT y profesor adjunto en la Pontificia Universidad Católica de Chile, enfocado en seguridad computacional, sistemas de software y cómo los equipos hacen que la tecnología funcione." },
		],
		footer: ["Santiago, Chile", "Español · Inglés · Italiano"],
	},
};

export const repos = {
	en: {
		lang: "en",
		altPath: "/es/repos/",
		description: "Selected public and private repositories by Ignacio Parada.",
		title: "Repositories · Ignacio Parada",
		nav: { home: "Home", cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Code & projects",
		heading: "Repositories I’m working with.",
		lede: "A short map of selected repositories, spanning teaching material, infrastructure automation, OpenClaw tooling, and this site itself. Private repositories are listed for context, but are not publicly accessible.",
		publicLabel: "Public",
		privateLabel: "Private",
		view: "View on GitHub →",
		privateNote: "Private repository — access restricted",
		footer: ["Santiago, Chile", "Public and private repository overview"],
	},
	es: {
		lang: "es",
		altPath: "/repos/",
		description: "Repositorios públicos y privados seleccionados de Ignacio Parada.",
		title: "Repositorios · Ignacio Parada",
		nav: { home: "Inicio", cv: "CV", repos: "Repos", email: "Email", linkedin: "LinkedIn" },
		kicker: "Código y proyectos",
		heading: "Repositorios en los que trabajo.",
		lede: "Un mapa breve de repositorios seleccionados: material docente, automatización de infraestructura, herramientas de OpenClaw y este sitio. Los repositorios privados aparecen solo como contexto y no son accesibles públicamente.",
		publicLabel: "Público",
		privateLabel: "Privado",
		view: "Ver en GitHub →",
		privateNote: "Repositorio privado — acceso restringido",
		footer: ["Santiago, Chile", "Resumen de repositorios públicos y privados"],
	},
};

export const repoItems = [
	{ name: "homepage", visibility: "Public", url: "https://github.com/nachoparada/homepage", stack: "Astro · JavaScript", description: { en: "The source for this personal website, built with Astro and deployed automatically through Cloudflare Pages.", es: "El código fuente de este sitio personal, construido con Astro y desplegado automáticamente mediante Cloudflare Pages." } },
	{ name: "IIC2531", visibility: "Public", url: "https://github.com/nachoparada/IIC2531", stack: "Marp · Markdown", description: { en: "Course material and Marp presentations for IIC2531, Computer Security at Pontificia Universidad Católica de Chile.", es: "Material del curso y presentaciones en Marp para IIC2531, Seguridad Computacional en la Pontificia Universidad Católica de Chile." } },
	{ name: "IIC2531-26-01-labs", visibility: "Public", url: "https://github.com/nachoparada/IIC2531-26-01-labs", stack: "Python · C · Shell · Assembly", description: { en: "Lab material and supporting code for the 2026-01 edition of IIC2531, focused on practical computer security exercises.", es: "Material de laboratorios y código de apoyo para la versión 2026-01 de IIC2531, enfocado en ejercicios prácticos de seguridad computacional." } },
	{ name: "disc-mods", visibility: "Private", url: null, stack: "OpenClaw · Agent skills · Security validation", description: { en: "Private extended-skill modules for sandboxed agents in The Grid, enabling privileged operations through validated, security-aware disc-mod packages.", es: "Módulos privados de habilidades extendidas para agentes sandboxed en The Grid, que permiten operaciones privilegiadas mediante paquetes validados y conscientes de seguridad." } },
	{ name: "io-tower", visibility: "Private", url: null, stack: "Chrome Extension · Browser automation", description: { en: "Private OpenClaw browser relay extension that connects a browser to OpenClaw Gateway for remote AI-powered navigation, clicking, typing, and extraction.", es: "Extensión privada de navegador para OpenClaw que conecta el browser con OpenClaw Gateway para navegación, clicks, escritura y extracción asistidas por IA." } },
	{ name: "nexus", visibility: "Private", url: null, stack: "Python · HTML · Shell", description: { en: "Private multi-server management system for OpenClaw deployments, used to monitor servers, collect configuration, track agents and disc-mods, and coordinate deployments.", es: "Sistema privado de gestión multi-servidor para despliegues de OpenClaw, usado para monitorear servidores, recolectar configuración, rastrear agentes y disc-mods, y coordinar despliegues." } },
	{ name: "the-grid", visibility: "Private", url: null, stack: "Ansible · OpenClaw · Infrastructure", description: { en: "Private Ansible deployment system for OpenClaw: automated, hardened host setup with security posture, service configuration, and operational automation.", es: "Sistema privado de despliegue Ansible para OpenClaw: configuración automatizada y endurecida de hosts, postura de seguridad, configuración de servicios y automatización operacional." } },
	{ name: "openclaw-ansible", visibility: "Public", url: "https://github.com/nachoparada/openclaw-ansible", stack: "Shell · Ansible · Jinja", description: { en: "Automated, hardened OpenClaw installation with Tailscale VPN, UFW firewall, Docker isolation, and multi-OS deployment support.", es: "Instalación automatizada y endurecida de OpenClaw con VPN Tailscale, firewall UFW, aislamiento Docker y soporte multi-OS." } },
];
